.PHONY: clean All

All:
	@echo "----------Building project:[ HTTP-Server - Debug ]----------"
	@"$(MAKE)" -f  "HTTP-Server.mk"
clean:
	@echo "----------Cleaning project:[ HTTP-Server - Debug ]----------"
	@"$(MAKE)" -f  "HTTP-Server.mk" clean
